### PR TITLE
Added install with Vim-plug documentation and a requirments.txt

### PR DESCRIPTION
**Pull request by sanguis**
As I mentioned on #44 this will take advantage of https://github.com/junegunn/vim-plug's ability to run shell scripts as part of the plugin installation.

That means one can't forget to install the required Python binding, as it's one step

### CODE REVIEW

**Comment by Shougo** [comment]
I think `vim-hug-neovim-rpc` dependency is needed.

**Comment by sanguis** [comment]
@Shougo we could add it to the documentation or PR the other project?

**Comment by Shougo** [comment]
It can be added the PR.

**Comment by sanguis** [comment]
It's too bad the idea of the [Plugfile](https://github.com/junegunn/vim-plug/wiki/plugfile) was dropped, this would have added true recursive package managment to Vim

**Comment by sanguis** [comment]
Closing as I redid this work in an isolated branch in #46

**Pull request closed without merging**
