### PR TITLE
make python exe detection more reliable for vim8

### PR DESCRIPTION
**Pull request by skeept**

### CODE REVIEW

**Comment by skeept** [comment]
I don't use neovim but I tested the pull request with windows and in cygwin and it works well in vim8 in both environments.

**Comment by roxma** [comment]
I think the `python3` requirement is specified clearly in the README and you should follow that. I don't think it's worth adding the complexity. In case I need to explain how it works when it does not work.

Especially, `python` is not a good candidate, it points to python2 on many linux distros.

**Comment by skeept** [comment]
The requirement is listed but the problem is that I need would like to sync my vim configuration over different machines I have have to add logic for each of the machines which is not so nice.
Even in the same machine I am using it with windows and with cygwin so that creates issues.
The patch I propose can fix these issues.

You already have some logic there for neovim:

`python import sys
 let g:_yarp_py = pyeval('sys.executable')`

This would also work for vim, but this is incorrect because sys.executable can point to vim instead of python in windows.

The code I propose is an enhancement over that.

Python3 is a better candidate than python, because as you say sometimes python can be pointing to python2.
In the windows python I use there is no python3.exe the executable name is simply python.exe. 

So the logic I add there is to consider python3 as a candidate before python.

**Comment by hokorobi** [comment]
How about using `py3eval('sys.exec_prefix')` for Vim?

**Comment by hokorobi** [comment]
> How about using py3eval('sys.exec_prefix') for Vim?

Like [this](https://github.com/hokorobi/nvim-yarp/commit/fc67e3ff995ed01b555c0c0f302dcdfa35dfb439).

**Comment by roxma** [comment]
@hokorobi 

Thanks. I  prefer using `sys.exec_prefix`. I'll test it when I have some free time.

**Comment by roxma** [comment]
Closing...

`sys.exec_prefix` could be the same for `python2` and `python3`.

I don't want to implicitly take `python` instead when `python3` is not available. It's hard to cover all use cases. It's not worth the complexity.

Just set `g:python3_host_prog` manually when you need customization.

**Comment by skeept** [comment]
I think it would be worth to try to take this burden off the user.
It may add a little complexity but it would not be that hard.

But it's your call, as for me I have decided to go the other way and
actually stop using all plugins that use python. I don't add additional
configuration for each plugin.
I will miss denite.

Thanks for considering,

Regards,

**Pull request closed without merging**
